#!/usr/bin/env python3
"""Convert weather icon PNGs to compressed GIF bytes in flash (weather-code lookup).

Source icons come from c0wsaysmoo/plane-tracker-rgb-pi (its-a-plane-python/icons),
named by Tomorrow.io full-day weather codes (e.g. 10000 = clear day, 10001 = night).

Usage:
  python tools/weather_icons_to_header.py [--download] [SRC_DIR] [OUT_HEADER]

  --download   Fetch the icon PNGs into SRC_DIR from GitHub before converting.
"""

from __future__ import annotations

import io
import json
import sys
import urllib.request
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Pillow required: pip install Pillow")
    sys.exit(1)

MAX_W = 72
MAX_H = 72
REPO = "c0wsaysmoo/plane-tracker-rgb-pi"
ICON_DIR_CANDIDATES = [
    "its-a-plane-python/icons",
    "icons",
]
DEFAULT_SRC = Path(__file__).resolve().parent.parent / "data" / "weather_icons"
DEFAULT_OUT = (
    Path(__file__).resolve().parent.parent / "include" / "data" / "weather_icons_lookup.h"
)


def http_get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "flightscnr-icons"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def download_icons(dest: Path) -> int:
    dest.mkdir(parents=True, exist_ok=True)
    for icon_dir in ICON_DIR_CANDIDATES:
        api = f"https://api.github.com/repos/{REPO}/contents/{icon_dir}"
        try:
            listing = json.loads(http_get(api).decode("utf-8"))
        except Exception as exc:  # noqa: BLE001
            print(f"  list {icon_dir}: {exc}")
            continue
        if not isinstance(listing, list):
            continue
        count = 0
        for item in listing:
            name = item.get("name", "")
            if not name.lower().endswith(".png"):
                continue
            url = item.get("download_url")
            if not url:
                continue
            try:
                (dest / name).write_bytes(http_get(url))
                count += 1
            except Exception as exc:  # noqa: BLE001
                print(f"  skip {name}: {exc}")
        if count:
            print(f"Downloaded {count} icons from {icon_dir}")
            return count
    print("No icons downloaded (check the repo path / network).")
    return 0


def parse_code(png: Path) -> int | None:
    stem = png.stem
    if not stem.isdigit():
        return None
    code = int(stem)
    if code <= 0 or code > 65535:
        return None
    # The device only requests 5-digit full-day codes (weatherCode*10, +1 at
    # night), so 4-digit base-code icons would be dead weight in flash. Skip them.
    if code < 10000:
        return None
    return code


def resize_preserve_aspect(image: Image.Image, max_w: int, max_h: int) -> Image.Image:
    aspect = image.size[0] / image.size[1]
    if aspect > 1:
        size = (max_w, max(1, int(max_w / aspect)))
    else:
        size = (max(1, int(max_h * aspect)), max_h)
    return image.resize(size, Image.Resampling.LANCZOS)


def emit_u8_array(name: str, data: bytes) -> str:
    lines: list[str] = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        parts = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"  {parts}")
    body = ",\n".join(lines)
    return f"constexpr uint8_t {name}[] PROGMEM = {{\n{body}\n}};\n"


def main() -> int:
    args = [a for a in sys.argv[1:] if a != "--download"]
    want_download = "--download" in sys.argv[1:]
    src_dir = Path(args[0]) if len(args) > 0 else DEFAULT_SRC
    out_path = Path(args[1]) if len(args) > 1 else DEFAULT_OUT

    if want_download or not src_dir.is_dir() or not any(src_dir.glob("*.png")):
        download_icons(src_dir)

    if not src_dir.is_dir():
        print(f"Skip weather icons: {src_dir} not found")
        return 0

    pngs = sorted(src_dir.glob("*.png"))
    entries: list[tuple[int, str]] = []
    blob_sources: list[str] = []
    blob_meta: dict[int, tuple[int, int, int]] = {}
    total_bytes = 0

    for png in pngs:
        code = parse_code(png)
        if code is None:
            continue
        image = Image.open(png).convert("RGBA")
        image = resize_preserve_aspect(image, MAX_W, MAX_H)
        w, h = image.size
        byte_io = io.BytesIO()
        image.save(byte_io, optimize=True, format="GIF")
        gif = byte_io.getvalue()
        total_bytes += len(gif)
        sym = f"wx_icon_{code}"
        blob_sources.append(emit_u8_array(f"{sym}_gif", gif))
        blob_meta[code] = (w, h, len(gif))
        entries.append((code, sym))
        image.close()

    entries.sort(key=lambda e: e[0])

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as out:
        out.write("// Auto-generated by tools/weather_icons_to_header.py — do not edit.\n")
        out.write("#pragma once\n\n")
        out.write("#include <cstddef>\n#include <cstdint>\n\n")
        out.write("namespace data::weather_icons {\n\n")
        out.write(f"constexpr int kMaxIconW = {MAX_W};\n")
        out.write(f"constexpr int kMaxIconH = {MAX_H};\n\n")
        out.write("constexpr uint16_t kTransparentRgb565 = 0xF81F;\n\n")
        out.write("struct IconBlob {\n  uint16_t w;\n  uint16_t h;\n")
        out.write("  uint32_t size;\n  const uint8_t* gif;\n};\n\n")
        out.write("struct Entry {\n  uint16_t code;\n  const IconBlob* icon;\n};\n\n")

        if not entries:
            out.write("constexpr size_t kCount = 0;\n")
            out.write("constexpr Entry kEntries[] = {{0, nullptr}};\n\n")
            out.write("}  // namespace data::weather_icons\n")
            print(f"Wrote {out_path}: 0 icons (no PNGs found in {src_dir})")
            return 0

        for src in blob_sources:
            out.write(src)
            out.write("\n")
        for code, (w, h, size) in sorted(blob_meta.items()):
            out.write(
                f"constexpr IconBlob kBlob_{code} = "
                f"{{ {w}, {h}, {size}, wx_icon_{code}_gif }};\n"
            )
        out.write("\n")
        out.write(f"constexpr size_t kCount = {len(entries)};\n\n")
        out.write("constexpr Entry kEntries[] PROGMEM = {\n")
        for code, _sym in entries:
            out.write(f"  {{{code}, &kBlob_{code}}},\n")
        out.write("};\n\n")
        out.write("}  // namespace data::weather_icons\n")

    print(
        f"Wrote {out_path}: {len(entries)} icons ({total_bytes / 1024:.0f} KiB)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
